server:
  port: 8081

spring:
  application:
    name: produto-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/produto_db}
    username: ${SPRING_DATASOURCE_USERNAME:rpe}
    password: ${SPRING_DATASOURCE_PASSWORD:rpe}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
